# Generated by Django 5.2.8 on 2025-11-17 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to='Management.product')),
                ('item_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_orders', to='Management.product')),
            ],
        ),
    ]
