# Generated by Django 5.2.8 on 2025-11-17 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Management.product'),
        ),
    ]
