# Generated by Django 5.2.8 on 2025-11-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_rename_customer_name_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
