# Generated by Django 5.2.8 on 2025-11-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
